FROM positivly/prisma-binaries:latest as prisma
FROM node:16.9.0-alpine3.14

RUN npm install -g pnpm@6.31.0
RUN apk add g++ make python3

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install

VOLUME [ "/usr/src/app/node_modules" ]

RUN mkdir ./src
RUN mkdir ./prisma
RUN mkdir ./.images

VOLUME ["/usr/src/app/.images"]

# Set prisma environment:
ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
    PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
    PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
    PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
    PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
    PRISMA_CLIENT_ENGINE_TYPE=binary
COPY --from=prisma /prisma-engines/query-engine /prisma-engines/migration-engine /prisma-engines/introspection-engine /prisma-engines/prisma-fmt /prisma-engines/

COPY tsconfig.json ./

CMD pnpm run start:dev