FROM node:16.9.0-alpine3.14

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install

COPY ./src ./src
COPY ./prisma ./prisma

CMD pnpm run start:dev