FROM node:16.9.0-alpine3.14

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install

VOLUME [ "/usr/src/app/node_modules" ]

RUN mkdir ./src
RUN mkdir ./prisma
RUN mkdir ./.images

VOLUME ["/usr/src/app/.images"]

COPY tsconfig.json ./

CMD pnpm run start:dev