components:
  parameters:
    DriverId:
      name: id
      schema:
        type: string
      in: path
      required: true
      description: The driver's ID.
    DriverImageFilename:
      name: filename
      schema:
        type: string
      in: path
      required: true
      description: The image's filename.
    SearchDriversCriteriaId:
      name: id
      schema:
        type: string
      in: query
      description: The ID match criteria.
    SearchDriversCriteriaFirstNameTH:
      name: firstNameTH
      schema:
        type: string
      in: query
      description: The first name (Thai) match criteria.
    SearchDriversCriteriaLastNameTH:
      name: lastNameTH
      schema:
        type: string
      in: query
      description: The last name (Thai) match criteria.
    SearchDriversCriteriaFirstNameEN:
      name: firstNameEN
      schema:
        type: string
      in: query
      description: The first name (English) match criteria.
    SearchDriversCriteriaLastNameEN:
      name: lastNameEN
      schema:
        type: string
      in: query
      description: The last name (English) match criteria.
    SearchDriversCriteriaGender:
      name: gender
      schema:
        type: string
        enum: [MALE, FEMALE, NOT_SPECIFIED]
      in: query
      description: The gender match criteria.
    SearchDriversCriteriaNationalId:
      name: nationalId
      schema:
        type: string
      in: query
      description: The national Id match criteria.
    SearchDriversCriteriaCarDrivingLicenseId:
      name: carDrivingLicenseId
      schema:
        type: string
      in: query
      description: The car driving license Id match criteria.
    SearchDriversCriteriaImageFilename:
      name: imageFilename
      schema:
        type: string
      in: query
      description: The image's filename criteria.
    SearchDriversCriteriaStartBirthDate:
      name: startBirthDate
      schema:
        type: string
      in: query
      description: The start birth date match criteria.
    SearchDriversCriteriaEndBirthDate:
      name: endBirthDate
      schema:
        type: string
      in: query
      description: The end birth date match criteria.
    SearchDriversCriteriaStartRegisterDate:
      name: startRegisterDate
      schema:
        type: string
      in: query
      description: The start register date match criteria.
    SearchDriversCriteriaEndRegisterDate:
      name: endRegisterDate
      schema:
        type: string
      in: query
      description: The end register date match criteria.
    SearchDriversCriteriaStatus:
      name: status
      schema:
        type: string
        enum: [ACTIVE, INACTIVE]
      in: query
      description: The status match criteria.
    SearchDriversCriteriaLimit:
      name: limit
      schema:
        type: integer
      in: query
      description: The pagination's limit.
    SearchDriversCriteriaOffset:
      name: offset
      schema:
        type: integer
      in: query
      description: The pagination's offset.
    SearchDriversCriteriaOrderBy:
      name: orderBy
      schema:
        type: string
      in: query
      description: The order by field.
    SearchDriversCriteriaOrderDir:
      name: orderDir
      schema:
        type: string
        enum: [asc, desc]
      in: query
      description: The order direction.
    GetDriverAccidentLogsCriteriaStartTime:
      name: startTime
      schema:
        type: string
        format: date-time
      in: query
      description: The start date-time in RFC-3339 format.
    GetDriverAccidentLogsCriteriaEndTime:
      name: endTime
      schema:
        type: string
        format: date-time
      in: query
      description: The end date-time in RFC-3339 format.
    GetECRInfluxQueryCarId:
      name: carId
      schema:
        type: string
      in: query
      description: The car's ID.
    GetECRInfluxQueryStartTime:
      name: startTime
      schema:
        type: string
      in: query
      description: The start of the log time range. (ISO-8601 or relative)
    GetECRInfluxQueryEndTime:
      name: endTime
      schema:
        type: string
      in: query
      description: The end of the log time range. (ISO-8601 or relative)
    GetECRInfluxQueryAggregate:
      name: aggregate
      schema:
        type: boolean
      in: query
      description: Do aggregate or not.
    GetDrowsinessInfluxQueryStartTime:
      name: startTime
      schema:
        type: string
      in: query
      description: The start of the log time range. (ISO-8601 or relative)
    GetDrowsinessInfluxQueryEndTime:
      name: endTime
      schema:
        type: string
      in: query
      description: The end of the log time range. (ISO-8601 or relative)
    GetDrowsinessInfluxQueryAggregate:
      name: aggregate
      schema:
        type: boolean
      in: query
      description: Do aggregate or not.
  schemas:
    CreateDriverDto:
      type: object
      properties:
        firstNameTH:
          type: string
          required: true
        lastNameTH:
          type: string
          required: true
        firstNameEN:
          type: string
          required: true
        lastNameEN:
          type: string
          required: true
        gender:
          type: string
          enum: [MALE, FEMALE, NOT_SPECIFIED]
        birthDate:
          type: string
          format: date
        nationalId:
          type: string
        carDrivingLicenseId:
          type: string
        username:
          type: string
          required: true
        password:
          type: string
          required: true
    UpdateDriverDto:
      type: object
      properties:
        firstNameTH:
          type: string
        lastNameTH:
          type: string
        firstNameEN:
          type: string
        lastNameEN:
          type: string
        gender:
          type: string
          enum: [MALE, FEMALE, NOT_SPECIFIED]
        birthDate:
          type: string
          format: date
        nationalId:
          type: string
        carDrivingLicenseId:
          type: string
    UpdateDriverImageDto:
      type: object
      properties:
        image:
          type: string
          format: binary
