components:
  parameters:
    CarId:
      name: id
      schema:
        type: string
      in: path
      required: true
      description: The car's ID.
    CarImageFilename:
      name: filename
      schema:
        type: string
      in: path
      required: true
      description: The image's filename.
    SearchCarsCriteriaId:
      name: id
      schema:
        type: string
      in: query
      description: The ID match criteria.
    SearchCarsCriteriaLicensePlate:
      name: licensePlate
      schema:
        type: string
      in: query
      description: The license plate match criteria.
    SearchCarsCriteriaModel:
      name: model
      schema:
        type: string
      in: query
      description: The model match criteria.
    SearchCarsCriteriaImageFilename:
      name: imageFilename
      schema:
        type: string
      in: query
      description: The image's filename criteria.
    SearchCarsCriteriaStatus:
      name: status
      schema:
        type: string
        enum: [ACTIVE, INACTIVE]
      in: query
      description: The status match criteria.
    SearchCarsCriteriaMinPassengers:
      name: minPassengers
      schema:
        type: number
      in: query
      description: The min passengers match criteria.
    SearchCarsCriteriaMaxPassengers:
      name: maxPassengers
      schema:
        type: number
      in: query
      description: The max passengers match criteria.
    SearchCarsCriteriaLimit:
      name: limit
      schema:
        type: integer
      in: query
      description: The pagination's limit.
    SearchCarsCriteriaOffset:
      name: offset
      schema:
        type: integer
      in: query
      description: The pagination's offset.
    SearchCarsCriteriaOrderBy:
      name: orderBy
      schema:
        type: string
      in: query
      description: The order by field.
    SearchCarsCriteriaOrderDir:
      name: orderDir
      schema:
        type: string
        enum: [asc, desc]
      in: query
      description: The order direction.
    GetCarAccidentLogsCriteriaStartTime:
      name: startTime
      schema:
        type: string
        format: date-time
      in: query
      description: The start date-time in RFC-3339 format.
    GetCarAccidentLogsCriteriaEndTime:
      name: endTime
      schema:
        type: string
        format: date-time
      in: query
      description: The end date-time in RFC-3339 format.
    GetPassengerInfluxQueryStartTime:
      name: startTime
      schema:
        type: string
      in: query
      description: The start of the log time range. (ISO-8601 or relative)
    GetPassengerInfluxQueryEndTime:
      name: endTime
      schema:
        type: string
      in: query
      description: The end of the log time range. (ISO-8601 or relative)
    GetPassengerInfluxQueryAggregate:
      name: aggregate
      schema:
        type: boolean
      in: query
      description: Do aggregate or not.
  schemas:
    CreateCarDto:
      type: object
      properties:
        licensePlate:
          type: string
          required: true
        model:
          type: string
          required: true
        cameras:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                required: true
    UpdateCarDto:
      type: object
      properties:
        licensePlate:
          type: string
          required: true
        model:
          type: string
          required: true
        cameras:
          type: object
          properties:
            connect:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    required: true
            disconnect:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    required: true
    UpdateCarImageDto:
      type: object
      properties:
        image:
          type: string
          format: binary
