@dashboardId = 61dfbeaa00ddd0e43f0a0c4f
@dashboardItem1Id = 61de5c12295cc738f774ac4e
@dashboardItem2Id = 61de5c31295cc738f774ac4f
@dashboardItem3Id = 61de5c3a295cc738f774ac50

### Create a new dashboard
POST http://localhost:3000/dashboards HTTP/1.1
Content-Type: application/json

{
  "name": "my-dashboard-1"
}

### Get all dashboards
GET http://localhost:3000/dashboards HTTP/1.1

### Get the specific dashboard
GET http://localhost:3000/dashboards/{{dashboardId}} HTTP/1.1

### Update the specific dashboard
PATCH  http://localhost:3000/dashboards/{{dashboardId}} HTTP/1.1
Content-Type: application/json

{
  "name": "my-dashboard-1-new"
}

### Delete the specific dashboard
DELETE  http://localhost:3000/dashboards/{{dashboardId}} HTTP/1.1

### Update items in the specific dashboard
PATCH  http://localhost:3000/dashboards/{{dashboardId}}/update-items HTTP/1.1
Content-Type: application/json

{
  "associations": [
    {
      "dashboardItemId": "{{dashboardItem1Id}}",
      "x": 0,
      "y": 0
    },
    {
      "dashboardItemId": "{{dashboardItem2Id}}",
      "x": 1,
      "y": 0
    },
    {
      "dashboardItemId": "{{dashboardItem3Id}}",
      "x": 0,
      "y": 1
    }
  ]
}
