@baseURL = http://localhost:5000
@dashboardId =
@dashboardItem1Id =
@dashboardItem2Id =
@dashboardItem3Id =

### Create a new dashboard
POST {{baseURL}}/dashboards HTTP/1.1
Content-Type: application/json

{
  "name": "my-dashboard-1",
  "default": true
}

### Get default dashboard
GET {{baseURL}}/dashboards?default=true HTTP/1.1

### Get all dashboards
GET {{baseURL}}/dashboards HTTP/1.1

### Get the specific dashboard
GET {{baseURL}}/dashboards/{{dashboardId}} HTTP/1.1

### Update the specific dashboard
PATCH  {{baseURL}}/dashboards/{{dashboardId}} HTTP/1.1
Content-Type: application/json

{
  "name": "my-dashboard-1-new",
  "default": true
}

### Delete the specific dashboard
DELETE  {{baseURL}}/dashboards/{{dashboardId}} HTTP/1.1

### Update items in the specific dashboard
PATCH  {{baseURL}}/dashboards/{{dashboardId}}/update-items HTTP/1.1
Content-Type: application/json

{
  "associations": [
    {
      "dashboardItemId": "{{dashboardItem1Id}}",
      "x": 0,
      "y": 0,
      "w": 1,
      "h": 1
    },
    {
      "dashboardItemId": "{{dashboardItem2Id}}",
      "x": 3,
      "y": 0,
      "w": 2,
      "h": 2
    },
    {
      "dashboardItemId": "{{dashboardItem3Id}}",
      "x": 0,
      "y": 2,
      "w": 3,
      "h": 3
    }
  ]
}