@dashboardId = 
@dashboardItem1Id = 
@dashboardItem2Id = 
@dashboardItem3Id = 

### Create a new dashboard
POST http://localhost:3000/dashboards HTTP/1.1
Content-Type: application/json

{
  "name": "my-dashboard-1",
  "default": true
}

### Get default dashboard
GET http://localhost:3000/dashboards?default=true HTTP/1.1

### Get all dashboards
GET http://localhost:3000/dashboards HTTP/1.1

### Get the specific dashboard
GET http://localhost:3000/dashboards/{{dashboardId}} HTTP/1.1

### Update the specific dashboard
PATCH  http://localhost:3000/dashboards/{{dashboardId}} HTTP/1.1
Content-Type: application/json

{
  "name": "my-dashboard-1-new",
  "default": true
}

### Delete the specific dashboard
DELETE  http://localhost:3000/dashboards/{{dashboardId}} HTTP/1.1

### Update items in the specific dashboard
PATCH  http://localhost:3000/dashboards/{{dashboardId}}/update-items HTTP/1.1
Content-Type: application/json

{
  "associations": [
    {
      "dashboardItemId": "{{dashboardItem1Id}}",
      "x": 0,
      "y": 0
    },
    {
      "dashboardItemId": "{{dashboardItem2Id}}",
      "x": 1,
      "y": 0
    },
    {
      "dashboardItemId": "{{dashboardItem3Id}}",
      "x": 0,
      "y": 1
    }
  ]
}