@baseURL=http://localhost:5000

### Register a user
POST {{baseURL}}/register
Content-Type: application/json

{
    "username": "admin",
    "password": "mypassword",
    "role": "ADMIN"
}

### Login
POST {{baseURL}}/login
Content-Type: application/json

{
    "username": "admin",
    "password": "mypassword",
    "role": "ADMIN"
}

### Logout
POST {{baseURL}}/logout
Content-Type: application/json

{}

### Get current user
GET {{baseURL}}/currentuser